-- MySQL Script generated by MySQL Workbench
-- Sun Oct 13 22:02:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_jogodobicho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_jogodobicho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_jogodobicho` DEFAULT CHARACTER SET utf8 ;
USE `db_jogodobicho` ;

-- -----------------------------------------------------
-- Table `db_jogodobicho`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jogodobicho`.`endereco` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NULL,
  `logradouro` VARCHAR(255) NULL,
  `numero` INT NULL,
  `cidade` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  `complemento` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NULL,
  `pais` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jogodobicho`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jogodobicho`.`usuarios` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(255) NULL,
  `dataNasc` DATE NULL,
  `genero` VARCHAR(1) NULL,
  `nomeMae` VARCHAR(255) NULL,
  `cpf` VARCHAR(11) NULL,
  `email` VARCHAR(255) NULL,
  `celular` VARCHAR(11) NULL,
  `fixo` VARCHAR(11) NULL,
  `created_at` TIMESTAMP DEFAULT current_timestamp,
  `updated_at` TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp,
  `endereco_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC),
  INDEX `fk_usuarios_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_usuarios_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `db_jogodobicho`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jogodobicho`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jogodobicho`.`credenciais` (
  `nomeUsuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `administrador` TINYINT(1) NOT NULL DEFAULT 0,
  `tentativasLogin` TINYINT(3) NOT NULL DEFAULT 0,
  `contaTravada` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`nomeUsuario`),
  UNIQUE INDEX `ID_UNIQUE` (`nomeUsuario` ASC),
  INDEX `fk_credenciais_usuarios1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_credenciais_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_jogodobicho`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jogodobicho`.`userLogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jogodobicho`.`registroDeEntradas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `respostaA2F` VARCHAR(255) NOT NULL,
  `nomeUsuario` VARCHAR(255) NOT NULL,
  `sessao_id` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC),
  INDEX `fk_registroDeEntradas_credenciais1_idx` (`nomeUsuario` ASC),
  CONSTRAINT `fk_registroDeEntradas_credenciais1`
    FOREIGN KEY (`nomeUsuario`)
    REFERENCES `db_jogodobicho`.`credenciais` (`nomeUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
